### ISSUE TITLE
License needs to be changed in order to continue to be listed at Redis Modules

### ISSUE THREAD

**Issue by brennanfee** [RedisLabsModules/topk#8]
This has got to be fixed in order to actually be open source. The Redis modules site explicitly states, "Only modules under an OSI approved license are listed here." Commons Clause IS NOT OSI APPROVED.

**Comment by itamarhaber** [comment]
Hello @brennanfee 

It appears like you have too much time on your hands, as you've decided to open this issue in multiple repositories. It would have been better if you'd actually bothered looking at the license of this repository - AFAIK AGPL is OSI approved.

Closing this issue.

**Comment by brennanfee** [comment]
My bad, you are correct.  Thanks!
